#!/usr/bin/env node
// Generates the machine-derived half of the Hextra agent skill.
//
//   skills/hextra/references/shortcodes.md  <- layouts/_shortcodes/**/*.html
//                                              + .vscode/hextra.code-snippets
//   skills/hextra/references/icons.md       <- data/icons.yaml
//
// The shortcode templates are the authority: they define which parameters
// exist, which are required, what the defaults are, and whether a shortcode is
// paired. Their doc comments carry `@param` and `@example` tags, so most of the
// prose comes from the implementation too.
//
// The VS Code snippets are a secondary source, used for two things the
// templates express poorly: enum choices (a snippet writes
// `${1|grid,mosaic|}`, where a template only mentions them in prose) and
// complete copy-paste examples (a template's `@example` is one terse line, and
// a few are mangled by Prettier's Go-template parser). Snippets also cover
// front matter and code fences, which are not shortcodes at all.
//
// Where the two disagree, the template wins and the difference is reported.
//
//   node scripts/build-skill.mjs            write the files
//   node scripts/build-skill.mjs --check    exit 1 if the files are stale
//   node scripts/build-skill.mjs --strict   also exit 1 on any source mismatch

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative, sep } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const shortcodeDir = join(root, "layouts", "_shortcodes");
const snippetsFile = join(root, ".vscode", "hextra.code-snippets");
const iconsFile = join(root, "data", "icons.yaml");
const outDir = join(root, "skills", "hextra", "references");

const BANNER = (sources) =>
  `<!-- Generated by scripts/build-skill.mjs from ${sources} — do not edit by hand.
     Regenerate with: npm run build:skill -->`;

// ---------------------------------------------------------------------------
// Go template parsing
// ---------------------------------------------------------------------------

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

/** Leading `{{- /* ... *​/ -}}` doc comment, if the file opens with one. */
function docComment(source) {
  const m = source.match(/^\s*\{\{-?\s*\/\*([\s\S]*?)\*\/\s*-?\}\}/);
  return m ? m[1] : "";
}

/**
 * `.Get` calls belonging to the shortcode itself.
 *
 * Two things masquerade as parameter reads and must not be counted: a `.Get`
 * on some other object (`$styles.Get`, `.Page.Store.Get`), which the lookbehind
 * rejects, and a `.Get` inside `{{ with .Parent }}`, where the dot is rebound
 * to the parent shortcode — `accordion-item` reads its parent's `mode` that
 * way. Tracking block depth is enough to spot the second case; the templates
 * never nest a parent scope inside another parent scope.
 */
function ownGetCalls(body) {
  const OPENS = /\{\{-?\s*(if|with|range|block|define)\b([^}]*)\}\}/;
  const ENDS = /\{\{-?\s*end\s*-?\}\}/;
  const GET = /(?<![\w])\.Get\s+(?:"([^"]+)"|(\d+))/g;

  const named = new Map();
  const positional = new Set();
  const parentParams = new Set();

  let depth = 0;
  let parentDepth = null;

  for (const action of body.split(/(?=\{\{)/)) {
    const inParentScope = parentDepth !== null;

    for (const m of action.matchAll(GET)) {
      if (m[2] !== undefined) {
        if (!inParentScope) positional.add(Number(m[2]));
        continue;
      }
      if (inParentScope) parentParams.add(m[1]);
      else if (!named.has(m[1])) named.set(m[1], {});
    }

    const open = action.match(OPENS);
    if (open) {
      if (open[1] === "with" && /\$?\.Parent\b/.test(open[2]) && parentDepth === null) {
        parentDepth = depth;
      }
      depth++;
    } else if (ENDS.test(action)) {
      depth--;
      if (parentDepth !== null && depth <= parentDepth) parentDepth = null;
    }
  }

  return { named, positional, parentParams };
}

/** `.Get "x" | default VALUE` — the default, and any deprecated alias. */
function defaultsFor(body) {
  const out = new Map();
  const re = /(?<![\w])\.Get\s+"([^"]+)"\s*\|\s*default\s+(\([^)]*\)|"[^"]*"|\S+)/g;
  for (const m of body.matchAll(re)) {
    const [, name, raw] = m;
    const alias = raw.match(/\.Get\s+"([^"]+)"/);
    const entry = out.get(name) ?? {};
    if (alias) entry.alias = alias[1];
    else if (/\.Get\s+\d/.test(raw)) entry.positional = true;
    // `| default $someVar` resolves at render time; there is no literal to show.
    else if (!raw.startsWith("$")) entry.default = raw.replace(/^"|"$/g, "");
    out.set(name, entry);
  }
  return out;
}

/** Parameters an `errorf` names as required. */
function requiredFrom(body) {
  const out = new Set();
  for (const m of body.matchAll(/requires (?:a|an|at least one) '([^']+)'/g)) out.add(m[1]);
  for (const m of body.matchAll(/missing required '([^']+)'/g)) out.add(m[1]);
  return out;
}

function parseDoc(comment) {
  const lines = comment.split("\n").map((l) => l.replace(/^\s*/, ""));
  const params = [];
  const positionalDocs = [];
  const examples = [];
  const prose = [];
  const deprecated = [];

  for (const line of lines) {
    const param = line.match(/^@param\s+\{([^}]*)\}\s+(\S+)\s*(.*)$/);
    if (param) {
      // `@param {string} 0` and `0..n` document positional arguments, which
      // are read with `.Get 0` rather than by name.
      //
      // A name may carry both spellings, as in `0|src`: the value can be passed
      // positionally or under that name. Splitting on the bar records each side,
      // so the named half is not lost to the leading digit - it used to be, and
      // the parameter was then reported as undocumented and printed in the
      // reference as "Undocumented in the template" despite being documented.
      const desc = param[3].trim();
      const names = param[2].split("|").filter(Boolean);
      if (names.some((name) => /^\d/.test(name))) positionalDocs.push(desc);
      for (const name of names.filter((name) => !/^\d/.test(name))) {
        params.push({ type: param[1], name, desc });
      }
      continue;
    }
    // `@deprecated name Use `x` instead.` documents a parameter the template
    // still accepts but nobody should reach for: an old spelling kept working,
    // or one that warns at build time. Without it such a parameter looks like an
    // omission to the cross-check, and the reference advertised it as an
    // ordinary parameter with no description and no warning.
    const deprecatedTag = line.match(/^@deprecated\s+(\S+)\s*(.*)$/);
    if (deprecatedTag) {
      deprecated.push({ name: deprecatedTag[1], note: deprecatedTag[2].trim() });
      continue;
    }
    const example = line.match(/^@example\s+(.*)$/);
    if (example) {
      examples.push(example[1].trim());
      continue;
    }
    if (/^@\w+/.test(line)) continue;
    if (params.length === 0 && examples.length === 0) prose.push(line);
  }

  return {
    // The first paragraph is the summary; later paragraphs are implementation
    // notes aimed at theme developers, not at the person writing content.
    description:
      prose
        .join("\n")
        .trim()
        .split(/\n\s*\n/)[0]
        ?.replace(/\s+/g, " ")
        .trim() ?? "",
    params,
    positionalDocs,
    examples,
    deprecated,
  };
}

function parseShortcode(file) {
  const source = readFileSync(file, "utf8");
  const name = relative(shortcodeDir, file)
    .split(sep)
    .join("/")
    .replace(/\.html$/, "");
  const comment = docComment(source);
  const body = source.slice(comment ? source.indexOf(comment) + comment.length : 0);

  const doc = parseDoc(comment);
  const { named, positional, parentParams } = ownGetCalls(body);
  const defaults = defaultsFor(body);
  const required = requiredFrom(body);

  // An `@example` must end in `}}` to be usable; Prettier's Go-template parser
  // reflows a few of them across lines inside the comment.
  const examples = doc.examples.filter((e) => /\}\}\s*$/.test(e) && !/^\w+:/.test(e));

  const documented = new Map(doc.params.map((p) => [p.name, p]));
  const deprecated = new Map(doc.deprecated.map((d) => [d.name, d.note]));
  const paramNames = [...new Set([...named.keys(), ...documented.keys(), ...deprecated.keys()])].sort();

  const params = paramNames.map((pname) => {
    const d = documented.get(pname);
    const meta = defaults.get(pname) ?? {};
    const desc = d?.desc ?? "";
    const inCode = named.has(pname);

    const declaredDefault = desc.match(/\bDefaults? (?:to )?([^.]+)\./i)?.[1];
    const enumFromDesc = desc.match(/\bOne of ([^.]+)\./i)?.[1];

    return {
      name: pname,
      type: d?.type ?? "",
      desc,
      inCode,
      // A deprecated parameter is documented - just not recommended - so it is
      // neither a gap nor an undescribed row.
      documented: Boolean(d) || deprecated.has(pname),
      deprecated: deprecated.get(pname),
      required: required.has(pname) || /\bRequired\b/.test(desc),
      // A default stated in the doc comment is the readable one; fall back to
      // the literal in the template only when the comment says nothing.
      default: declaredDefault?.trim() ?? meta.default,
      alias: meta.alias,
      positionalAlias: Boolean(meta.positional),
      enum: enumFromDesc
        ? enumFromDesc
            .split(/,\s*|\s+or\s+/)
            .map((v) => v.replace(/\(default\)/i, "").trim())
            .filter(Boolean)
        : undefined,
    };
  });

  return {
    name,
    file: relative(root, file),
    description: doc.description,
    params,
    positional: [...positional].sort(),
    positionalDocs: doc.positionalDocs,
    parentParams: [...parentParams],
    examples,
    paired: /(?<![\w])\.Inner(?:Deindent)?\b/.test(body),
    // Notation is a call-site decision, so the only evidence in the template is
    // how its own examples are written.
    percentNotation: doc.examples.some((e) => e.includes("{{%")),
    network: /resources\.GetRemote/.test(body),
    siteParams: [...new Set([...body.matchAll(/(?:site|\.Site)\.Params\.([A-Za-z][\w.]*)/g)].map((m) => m[1].replace(/\.$/, "")))].sort(),
  };
}

// ---------------------------------------------------------------------------
// Snippets (secondary source)
// ---------------------------------------------------------------------------

function cleanBody(lines) {
  return (
    lines
      .join("\n")
      // Collapse a choice to its first option so the example is valid, pasteable
      // code. The full list of options reaches the reader through the parameter
      // table, which is built from the same placeholder.
      .replace(/\$\{\d+\|([^|]*)\|\}/g, (_, choices) => choices.split(",")[0].trim())
      .replace(/\$\{\d+:([^}]*)\}/g, "$1")
      .replace(/\$\{\d+\}/g, "")
      .replace(/\$\d+/g, "")
      .replace(/\\\$/g, "$")
      .replace(/[ \t]+$/gm, "")
      .replace(/\n{3,}/g, "\n\n")
      .trim()
  );
}

/** Enum choices a snippet spells out, keyed by parameter name. */
function snippetEnums(rawBody) {
  const out = new Map();
  const re = /([\w-]+)=\\?"?\$\{\d+\|([^|]*)\|\}/g;
  for (const m of rawBody.matchAll(re)) {
    out.set(
      m[1],
      m[2].split(",").map((v) => v.trim())
    );
  }
  return out;
}

function loadSnippets() {
  const raw = JSON.parse(readFileSync(snippetsFile, "utf8"));
  return Object.entries(raw).map(([label, snippet]) => {
    const rawBody = snippet.body.join("\n");
    const example = cleanBody(snippet.body);
    const owner = example.match(/\{\{[<%]\s*([\w/-]+)/)?.[1] ?? null;
    return {
      label: label.replace(/^Hextra:\s*/, ""),
      prefix: snippet.prefix,
      description: snippet.description,
      example,
      enums: snippetEnums(rawBody),
      owner,
    };
  });
}

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------

const CATEGORIES = [
  {
    title: "Callouts and text",
    blurb: "Inline emphasis and short-form content.",
    names: ["callout", "lead", "keywords", "keyword", "badge", "stats", "stat", "swatches", "icon", "term"],
  },
  {
    title: "Layout and structure",
    blurb: "Containers. A child shortcode only works inside its parent.",
    names: [
      "cards",
      "card",
      "tabs",
      "tab",
      "steps",
      "details",
      "accordion",
      "accordion-item",
      "timeline",
      "timeline-item",
      "filetree/container",
      "filetree/folder",
      "filetree/file",
      "borderless-table",
    ],
  },
  {
    title: "Links and actions",
    blurb: "Navigation away from the page.",
    names: ["button", "cta", "email", "article", "list"],
  },
  {
    title: "Media",
    blurb: "Images, video, and rich embeds.",
    names: ["gallery", "gallery-item", "video", "youtube-lite", "pdf", "chart", "typeit", "asciinema", "jupyter"],
  },
  {
    title: "Code and content import",
    blurb: "Pull code or Markdown in from elsewhere.",
    names: ["gist", "codeimporter", "include"],
  },
  {
    title: "Repository cards",
    blurb: "Each fetches at build time. All of them go quiet when `params.remoteFetch.enable` is false.",
    names: ["github", "gitlab", "gitea", "forgejo", "codeberg", "huggingface", "ansible"],
  },
  {
    title: "Home page",
    blurb: "Only for a page with `layout: hextra-home`.",
    names: ["hextra/hero-badge", "hextra/hero-container", "hextra/hero-headline", "hextra/hero-subtitle", "hextra/hero-button", "hextra/hero-section", "hextra/feature-grid", "hextra/feature-card"],
  },
  {
    title: "Text direction",
    blurb: "Both require `{{% %}}` notation.",
    names: ["ltr", "rtl"],
  },
];

// Snippets that document something other than a shortcode.
const SNIPPET_SECTIONS = [
  {
    title: "Front matter",
    blurb: "Starting points for a page's front matter. Full key reference in `frontmatter.md`.",
    prefixes: ["hxfm-docs", "hxfm-section", "hxfm-blog", "hxfm-series", "hxfm-home", "hxfm-sidebar", "hxfm-width", "hxfm-cascade"],
  },
  {
    title: "Code fences and math",
    blurb: "Markdown handled by render hooks rather than shortcodes. See `markdown.md`.",
    prefixes: ["hxcode", "hxcode-lines", "hxcode-baseurl", "hxmermaid", "hxmath"],
  },
];

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function escapeCell(text) {
  return text.replace(/\|/g, "\\|").replace(/\n+/g, " ").trim();
}

function paramTable(shortcode, enums) {
  const rows = shortcode.params.filter((p) => p.inCode || p.documented);
  if (rows.length === 0) return [];

  const out = ["| Parameter | Type | Notes |", "| --- | --- | --- |"];
  for (const p of rows) {
    const notes = [];
    if (p.required) notes.push("**Required.**");
    if (p.desc) {
      notes.push(
        escapeCell(
          p.desc
            .replace(/\s*Required\.\s*/, " ")
            .replace(/\s*Defaults? (?:to )?[^.]+\.\s*/i, " ")
            .replace(/\s*One of [^.]+\.\s*/i, " ")
            .trim()
        )
      );
    }

    const choices = enums.get(p.name) ?? p.enum;
    // A boolean's "one of true, false" carries no information the type lacks.
    const informative = choices?.length && !choices.every((c) => /^(true|false)$/.test(c));
    if (informative) notes.push(`One of \`${choices.join("`, `")}\`.`);
    // `| default ""` is an implementation detail, not a documented default.
    if (p.default) notes.push(`Default \`${p.default}\`.`);
    if (p.positionalAlias) notes.push("Also accepted as the first positional argument.");
    if (p.alias) notes.push(`Deprecated alias: \`${p.alias}\`.`);
    if (p.deprecated !== undefined) notes.push(`**Deprecated.** ${p.deprecated}`.trim());
    if (!p.documented) notes.push("_Undocumented in the template._");
    if (p.documented && !p.inCode) notes.push("_Documented but not read by the template._");

    out.push(`| \`${p.name}\` | ${p.type || "string"} | ${notes.join(" ") || "—"} |`);
  }
  return [...out, ""];
}

function renderShortcode(shortcode, snippets) {
  const mine = snippets.filter((s) => s.owner === shortcode.name);
  const enums = new Map();
  for (const s of mine) for (const [k, v] of s.enums) if (!enums.has(k)) enums.set(k, v);

  const notation = shortcode.percentNotation ? "{{% %}}" : "{{< >}}";
  const facts = [notation, shortcode.paired ? "paired" : "self-closing"];
  if (shortcode.positional.length > 0) facts.push("accepts positional arguments");
  if (shortcode.network) facts.push("fetches at build time");

  const out = [`### ${shortcode.name}`, "", facts.join(" · "), ""];
  if (shortcode.description) out.push(shortcode.description, "");

  out.push(...paramTable(shortcode, enums));

  if (shortcode.positionalDocs.length > 0) {
    out.push(`Positional: ${shortcode.positionalDocs.join(" ")}`, "");
  }

  if (shortcode.parentParams.length > 0) {
    out.push(`Reads from its parent: ${shortcode.parentParams.map((p) => `\`${p}\``).join(", ")}.`, "");
  }

  // Prefer a snippet example: it is complete and shows a child shortcode in
  // place, where `@example` is a single line.
  const examples = mine.length > 0 ? mine.map((s) => s.example) : shortcode.examples;
  if (examples.length > 0) {
    const fence = examples.some((e) => e.includes("```")) ? "````" : "```";
    out.push(`${fence}markdown`, examples.join("\n\n"), fence, "");
  }

  if (shortcode.siteParams.length > 0) {
    out.push(`Site config: ${shortcode.siteParams.map((p) => `\`params.${p}\``).join(", ")}.`, "");
  }

  return out.join("\n");
}

function renderSnippetEntry(snippet) {
  const isYaml = !snippet.example.startsWith("```") && !snippet.example.startsWith("$$");
  const fence = snippet.example.includes("```") ? "````" : "```";
  return [`### ${snippet.label}`, "", snippet.description, "", `${fence}${isYaml ? "yaml" : "markdown"}`, snippet.example, fence, ""].join("\n");
}

function buildShortcodes(shortcodes, snippets) {
  const byName = new Map(shortcodes.map((s) => [s.name, s]));
  const byPrefix = new Map(snippets.map((s) => [s.prefix, s]));
  const placed = new Set();

  const parts = [
    BANNER("layouts/_shortcodes/ and .vscode/hextra.code-snippets"),
    "",
    "# Shortcode reference",
    "",
    `Every shortcode the theme ships: ${shortcodes.length} of them, with parameters taken from the templates in \`layouts/_shortcodes/\` and examples from the theme's editor snippets.`,
    "",
    "## Rules that apply throughout",
    "",
    "- **Notation is not interchangeable.** A shortcode listed as `{{% %}}` renders its body as Markdown and breaks when written with angle brackets. The `{{% %}}` shortcodes are: " +
      shortcodes
        .filter((s) => s.percentNotation)
        .map((s) => `\`${s.name}\``)
        .join(", ") +
      ".",
    "- **A paired shortcode needs a closing tag.** Self-closing ones must not have one.",
    "- **Icon names are a closed set.** Any `icon`, `tagIcon`, or `badgeIcon` value must appear in `icons.md`. An unknown name renders nothing and raises no error.",
    "- **Build-time fetching can be switched off.** The shortcodes marked _fetches at build time_ all go quiet when `params.remoteFetch.enable` is `false`.",
    "",
  ];

  for (const category of CATEGORIES) {
    const found = category.names.map((n) => byName.get(n)).filter(Boolean);
    if (found.length === 0) continue;
    found.forEach((s) => placed.add(s.name));
    parts.push(`## ${category.title}`, "", category.blurb, "");
    for (const shortcode of found) parts.push(renderShortcode(shortcode, snippets));
  }

  const orphans = shortcodes.filter((s) => !placed.has(s.name));
  if (orphans.length > 0) {
    parts.push("## Uncategorized", "", "Add these to `CATEGORIES` in `scripts/build-skill.mjs`.", "");
    for (const shortcode of orphans) parts.push(renderShortcode(shortcode, snippets));
  }

  for (const section of SNIPPET_SECTIONS) {
    const found = section.prefixes.map((p) => byPrefix.get(p)).filter(Boolean);
    if (found.length === 0) continue;
    parts.push(`## ${section.title}`, "", section.blurb, "");
    for (const snippet of found) parts.push(renderSnippetEntry(snippet));
  }

  return (
    parts
      .join("\n")
      .replace(/\n{3,}/g, "\n\n")
      .trimEnd() + "\n"
  );
}

// ---------------------------------------------------------------------------
// icons.md
// ---------------------------------------------------------------------------

function buildIcons(yaml) {
  const names = yaml
    .split("\n")
    .map((line) => line.match(/^([A-Za-z0-9][\w-]*):/))
    .filter(Boolean)
    .map((m) => m[1])
    .sort();

  const columns = 4;
  const rows = Math.ceil(names.length / columns);
  const table = ["| | | | |", "| --- | --- | --- | --- |"];
  for (let r = 0; r < rows; r++) {
    const cells = [];
    for (let c = 0; c < columns; c++) {
      const name = names[c * rows + r];
      cells.push(name ? `\`${name}\`` : "");
    }
    table.push(`| ${cells.join(" | ")} |`);
  }

  return [
    BANNER("data/icons.yaml"),
    "",
    "# Icon names",
    "",
    `The ${names.length} icons bundled with the theme. Use a name from this list verbatim — an unknown name renders nothing, silently.`,
    "",
    "Valid wherever the theme takes an icon: the `icon` shortcode, and the `icon` parameter on `callout`, `card`, `cta`, `button`, `badge`, `accordion-item`, `timeline-item`, `stat`, `keyword`, `article`, `feature-card`, and the repository cards. Also `tagIcon` on `card`, `badgeIcon` on `timeline-item`, and `params.icon` on a `hugo.yaml` menu entry.",
    "",
    "```markdown",
    '{{< icon "sparkles" >}}',
    '{{< callout type="info" icon="lightning-bolt" >}}Heads up.{{< /callout >}}',
    "```",
    "",
    "Icons from an external provider are a separate path needing `params.icons.remote.enable`; see the `icon` entry in `shortcodes.md`.",
    "",
    "## Available names",
    "",
    ...table,
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Coverage of the hand-written references
// ---------------------------------------------------------------------------

// The generated references cannot drift, because they are rebuilt from the
// templates. The hand-written ones can, so every param the layouts read is
// checked against the file that is supposed to document it. This does not
// generate prose — it only reports what nobody has written about yet.
const layoutsDir = join(root, "layouts");

// Params that are deliberately absent from the author-facing references.
const COVERAGE_IGNORE = {
  // Read from a menu entry's `params`, not from a page. Documented as part of
  // the menu reference in site-config.md instead.
  page: new Map([
    ["icon", "menu entry param"],
    ["label", "menu entry param"],
    ["type", "menu entry param"],
    ["separator", "menu entry param"],
    ["weight", "ordering, covered under Ordering"],
  ]),
  // Asset-path overrides consumed by script partials. Covered collectively by
  // the "Vendored asset overrides" section rather than key by key.
  site: new Map([["Author", "Hugo's own author config, not a theme param"]]),
};

function paramsFromLayouts() {
  const site = new Set();
  const page = new Set();
  for (const file of walk(layoutsDir)) {
    if (!/\.(html|xml|txt|md|json)$/.test(file)) continue;
    const src = readFileSync(file, "utf8");
    // Blank out site params first so the page pass cannot rematch them.
    const remaining = src.replace(/(?:site|\.Site)\.Params\.([A-Za-z][\w.]*)/g, (_, path) => {
      site.add(path.replace(/\.$/, ""));
      return "\u0000";
    });
    for (const m of remaining.matchAll(/\.Params\.([A-Za-z][\w.]*)/g)) {
      page.add(m[1].replace(/\.$/, ""));
    }
  }
  return { site: [...site].sort(), page: [...page].sort() };
}

/**
 * Is `path` (e.g. "blog.list.pagerSize") actually written about?
 *
 * A bare word search is too generous: "Author" matches the skill's own
 * description, "assets" matches any `assets/` path, "favicon" matched a table
 * row about `static/`. Requiring the leaf to appear as a YAML key, in
 * backticks, or in dotted form rejects that class of false positive.
 */
function documents(text, path) {
  const leaf = path.split(".").pop();
  const e = leaf.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`(^|\\s)${e}:|\`[\\w.]*${e}[\\w.]*\`|\\.${e}\\b`, "m").test(text);
}

function coverageGaps() {
  const { site, page } = paramsFromLayouts();

  // Checked against the whole skill: a blog param may well be documented in
  // blog.md rather than site-config.md, and that counts.
  const skillText = walk(join(root, "skills", "hextra"))
    .filter((f) => f.endsWith(".md"))
    .map((f) => readFileSync(f, "utf8"))
    .join("\n");

  const gaps = [];
  for (const [kind, names] of [
    ["page", page],
    ["site", site],
  ]) {
    for (const path of names) {
      if (COVERAGE_IGNORE[kind].has(path.split(".")[0])) continue;
      if (!documents(skillText, path)) {
        gaps.push(`nothing documents the ${kind} param '${path}'`);
      }
    }
  }
  return gaps;
}

// ---------------------------------------------------------------------------
// Coverage of the theme's own documentation
// ---------------------------------------------------------------------------

// The docs site is not a source for the skill — it is prose written for people
// browsing a website, and it can drift from the code. It is a good *checklist*
// though: every topic the docs give a page to should be reachable from the
// skill. Each entry names a probe string that must appear somewhere under
// skills/hextra/ for the topic to count as covered.
const DOCS_TOPICS = [
  { page: "getting-started", probe: /hugo new site|getting started/i },
  { page: "guide/organize-files", probe: /_index\.md/ },
  { page: "guide/configuration", probe: /^params:/m },
  { page: "guide/markdown", probe: /task list/i },
  { page: "guide/syntax-highlighting", probe: /linenos/ },
  { page: "guide/latex", probe: /katex/i },
  { page: "guide/diagrams", probe: /mermaid/i },
  { page: "guide/deploy-site", probe: /deploy/i },
  { page: "advanced/multi-language", probe: /defaultContentLanguage/ },
  { page: "advanced/comments", probe: /giscus/i },
  { page: "advanced/customization", probe: /assets\/css\/custom\.css/ },
  { page: "advanced/additional-pages", probe: /layout: glossary/ },
  { page: "fork/google-fonts", probe: /params\.fonts|fonts:/ },
  { page: "fork/code-blocks", probe: /base_url/ },
  { page: "fork/blog", probe: /params\.blog|params:\s*\n\s*blog:/ },
  { page: "fork/accent-color", probe: /--color-accent-color-500/ },
  { page: "fork/color-palettes", probe: /--color-hextra-light/ },
  { page: "fork/favicons", probe: /favicon-dark\.svg/ },
  // Out of scope: these document the theme's own development workflow, not
  // how to author a site with it.
  { page: "fork/dev-tooling", skip: "theme development, covered by AGENTS.md" },
  { page: "fork/vscode-snippets", skip: "editor tooling, not site authoring" },
];

function docsGaps() {
  const skillText = walk(join(root, "skills", "hextra"))
    .filter((f) => f.endsWith(".md"))
    .map((f) => readFileSync(f, "utf8"))
    .join("\n");

  const gaps = [];
  for (const topic of DOCS_TOPICS) {
    if (topic.skip) continue;
    if (!topic.probe.test(skillText)) {
      gaps.push(`docs/content/docs/${topic.page}.md has no counterpart in the skill`);
    }
  }
  return gaps;
}

// ---------------------------------------------------------------------------
// Hugo's own shortcodes
// ---------------------------------------------------------------------------

// Hugo's embedded shortcodes as of v0.141+. Sourced from
// https://gohugo.io/shortcodes/ — there is no way to read them out of the
// binary, so this list is maintained by hand and checked two ways: every name
// must be documented in hugo-shortcodes.md, and any theme shortcode sharing a
// name shadows Hugo's and must be called out as a collision.
const HUGO_BUILTINS = ["details", "figure", "highlight", "instagram", "param", "qr", "ref", "relref", "vimeo", "x", "youtube"];

function hugoShortcodeGaps(shortcodes) {
  const file = join(outDir, "hugo-shortcodes.md");
  let text;
  try {
    text = readFileSync(file, "utf8");
  } catch {
    return ["hugo-shortcodes.md is missing"];
  }

  const gaps = [];
  for (const name of HUGO_BUILTINS) {
    if (!new RegExp(`^###?\\s+${name}\\b|\`${name}\``, "m").test(text)) {
      gaps.push(`hugo-shortcodes.md does not document Hugo's '${name}'`);
    }
  }

  // A theme shortcode with the same name wins, and silent shadowing is the
  // trap. Every built-in is named somewhere in this file by design, so the
  // check has to look inside the collisions section specifically.
  const collisions = text.match(/^## Name collisions[^]*?(?=^## )/m)?.[0] ?? "";
  for (const shortcode of shortcodes) {
    if (!HUGO_BUILTINS.includes(shortcode.name)) continue;
    if (!new RegExp(`\`${shortcode.name}\``).test(collisions)) {
      gaps.push(`'${shortcode.name}' shadows a Hugo built-in but is not listed under "Name collisions"`);
    }
  }
  return gaps;
}

// ---------------------------------------------------------------------------
// Plugin manifests
// ---------------------------------------------------------------------------

// The repo is installable as a Claude Code plugin, and is its own marketplace.
// VERSION is the repo's single source of truth — release.yml fires on it
// changing — so the manifests follow it rather than carrying a second number
// somebody has to remember. Only the version field is rewritten; every other
// field stays hand-editable.
const pluginDir = join(root, ".claude-plugin");
const pluginManifest = join(pluginDir, "plugin.json");
const marketplaceManifest = join(pluginDir, "marketplace.json");
const version = readFileSync(join(root, "VERSION"), "utf8").trim();

const serialize = (value) => JSON.stringify(value, null, 2) + "\n";

function buildPluginManifest() {
  const manifest = JSON.parse(readFileSync(pluginManifest, "utf8"));
  manifest.version = version;
  return serialize(manifest);
}

function buildMarketplaceManifest() {
  const manifest = JSON.parse(readFileSync(marketplaceManifest, "utf8"));
  for (const entry of manifest.plugins ?? []) {
    // Only this repo's own plugin tracks VERSION. An entry pointing at another
    // repository carries whatever version that repository published.
    if (typeof entry.source === "string" && entry.source.startsWith(".")) {
      entry.version = version;
    }
  }
  return serialize(manifest);
}

const KEBAB = /^[a-z0-9]+(-[a-z0-9]+)*$/;

function manifestGaps() {
  const gaps = [];
  let plugin;
  let marketplace;

  try {
    plugin = JSON.parse(readFileSync(pluginManifest, "utf8"));
  } catch (error) {
    return [`.claude-plugin/plugin.json is missing or invalid: ${error.message}`];
  }
  try {
    marketplace = JSON.parse(readFileSync(marketplaceManifest, "utf8"));
  } catch (error) {
    return [`.claude-plugin/marketplace.json is missing or invalid: ${error.message}`];
  }

  if (!KEBAB.test(plugin.name ?? "")) gaps.push(`plugin.json name '${plugin.name}' is not kebab-case`);
  if (!KEBAB.test(marketplace.name ?? "")) gaps.push(`marketplace.json name '${marketplace.name}' is not kebab-case`);
  if (!marketplace.owner?.name) gaps.push("marketplace.json is missing owner.name");

  const self = (marketplace.plugins ?? []).find((entry) => typeof entry.source === "string" && entry.source.startsWith("."));
  if (!self) {
    gaps.push("marketplace.json lists no plugin sourced from this repository");
  } else {
    // The entry's name is what users type in `/plugin install <name>@<market>`.
    // If it drifts from plugin.json the install resolves to nothing.
    if (self.name !== plugin.name) {
      gaps.push(`marketplace entry '${self.name}' does not match plugin.json name '${plugin.name}'`);
    }
    try {
      readFileSync(join(pluginDir, "..", self.source, ".claude-plugin", "plugin.json"));
    } catch {
      gaps.push(`marketplace entry source '${self.source}' has no .claude-plugin/plugin.json`);
    }
  }

  // Skills are namespaced <plugin>:<skill>, and a plugin's skills directory
  // defaults to ./skills/. A skill folder without SKILL.md installs as nothing.
  const skillsDir = join(root, "skills");
  const skills = readdirSync(skillsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);
  if (skills.length === 0) gaps.push("skills/ contains no skill directories");
  for (const skill of skills) {
    try {
      readFileSync(join(skillsDir, skill, "SKILL.md"));
    } catch {
      gaps.push(`skills/${skill}/ has no SKILL.md, so it installs as nothing`);
    }
  }

  return gaps;
}

// ---------------------------------------------------------------------------
// Cross-check
// ---------------------------------------------------------------------------

function mismatches(shortcodes, snippets) {
  const found = [];
  const byName = new Map(shortcodes.map((s) => [s.name, s]));

  for (const shortcode of shortcodes) {
    if (!shortcode.description && shortcode.params.length === 0 && shortcode.examples.length === 0) {
      found.push(`${shortcode.name}: template has no doc comment`);
    }
    for (const p of shortcode.params) {
      if (p.inCode && !p.documented) {
        found.push(`${shortcode.name}: reads '${p.name}' but has no @param for it`);
      }
      if (!p.inCode && p.documented && !shortcode.positional.length) {
        found.push(`${shortcode.name}: documents '${p.name}' but never reads it`);
      }
    }
  }

  // A snippet naming a parameter the template does not read is the failure
  // mode that hand-written snippets are prone to.
  for (const snippet of snippets) {
    const shortcode = snippet.owner ? byName.get(snippet.owner) : null;
    if (!shortcode) continue;
    const known = new Set(shortcode.params.map((p) => p.name));
    const opening = (snippet.example.match(/\{\{[<%]\s*[\w/-]+([^]*?)[%>]\}\}/)?.[1] ?? "")
      // A quoted value can itself contain `key=value` (`attributes="height=20"`).
      .replace(/"[^"]*"/g, '""');
    for (const m of opening.matchAll(/([\w-]+)=/g)) {
      if (!known.has(m[1])) {
        found.push(`${snippet.prefix}: uses '${m[1]}', which ${shortcode.name} does not read`);
      }
    }
  }

  return found;
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

const check = process.argv.includes("--check");
const strict = process.argv.includes("--strict");

const shortcodes = walk(shortcodeDir)
  .filter((f) => f.endsWith(".html"))
  .map(parseShortcode)
  .sort((a, b) => a.name.localeCompare(b.name));

const snippets = loadSnippets();

const outputs = [
  { path: join(outDir, "shortcodes.md"), content: buildShortcodes(shortcodes, snippets) },
  { path: join(outDir, "icons.md"), content: buildIcons(readFileSync(iconsFile, "utf8")) },
  { path: pluginManifest, content: buildPluginManifest() },
  { path: marketplaceManifest, content: buildMarketplaceManifest() },
];

let stale = 0;
for (const { path, content } of outputs) {
  const rel = relative(root, path);
  if (check) {
    let current = null;
    try {
      current = readFileSync(path, "utf8");
    } catch {
      /* missing counts as stale */
    }
    if (current === content) {
      console.log(`ok      ${rel}`);
    } else {
      console.error(`stale   ${rel}`);
      stale++;
    }
  } else {
    writeFileSync(path, content);
    console.log(`wrote   ${rel} (${content.split("\n").length} lines)`);
  }
}

const problems = [...mismatches(shortcodes, snippets), ...coverageGaps(), ...docsGaps(), ...hugoShortcodeGaps(shortcodes), ...manifestGaps()];
if (problems.length > 0) {
  console.error(`\n${problems.length} documentation gap(s) between the theme and the skill:`);
  for (const problem of problems) console.error(`  ${problem}`);
  console.error("\nThese do not fail the build unless --strict is passed.");
}

if (check && stale > 0) {
  console.error(`\n${stale} generated file(s) out of date. Run: npm run build:skill`);
  process.exit(1);
}
if (strict && problems.length > 0) process.exit(1);
