// Vendors third-party JavaScript used by shortcodes into assets/js/vendor/ so
// that neither builds nor page loads depend on a CDN.
//
// The theme's older integrations (Mermaid, PhotoSwipe) fetch from jsDelivr at
// build time via resources.GetRemote. That still requires network access on
// every build, which breaks offline and air-gapped builds and makes the output
// depend on whatever the CDN served that day. Vendoring pins the bytes.
//
// Run this when adding a library or bumping a version, then commit the result.
//
// Usage: npm run vendor:js

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "assets", "js", "vendor");

// Pinned deliberately: a floating version would make builds non-reproducible.
const packages = [
  {
    name: "chart.js",
    version: "4.5.0",
    url: "https://cdn.jsdelivr.net/npm/chart.js@4.5.0/dist/chart.umd.min.js",
    out: "chart.umd.min.js",
    license: "MIT",
  },
];

// Deliberately not vendored: TypeIt (typeitjs.com) is GPL-3.0 and requires a
// paid licence for commercial use. Committing it into an MIT theme would push
// that obligation onto every site built with it, so the `typeit` shortcode
// implements the effect directly instead.

mkdirSync(outDir, { recursive: true });

const manifest = ["# Generated by scripts/vendor-js.mjs — do not edit by hand.", ""];

for (const pkg of packages) {
  const res = await fetch(pkg.url);
  if (!res.ok) {
    console.error(`Failed to fetch ${pkg.url}: ${res.status}`);
    process.exit(1);
  }
  const body = await res.text();
  writeFileSync(join(outDir, pkg.out), body);
  manifest.push(`${pkg.out}: ${pkg.name}@${pkg.version} (${pkg.license})`);
  manifest.push(`  ${pkg.url}`);
  console.log(`${pkg.out}  ${pkg.name}@${pkg.version}  ${(body.length / 1024).toFixed(0)} KB`);
}

writeFileSync(join(outDir, "VERSIONS"), `${manifest.join("\n")}\n`);
console.log(`Wrote ${join(outDir, "VERSIONS")}`);
